### PR TITLE
Add a flag to allow the user to specify that if excess columns are fo…

### PR DESCRIPTION
**Pull request by kev3978**
…und in any given row, they can be ignored (e.g. row is truncated)

### CODE REVIEW

**Comment by doyaaaaaken** [comment]
Hi, @kev3978. Thanks for your pull request!
What is the difference between this `ignoreExcessCols` option and the `skipMissMatchedRow` option?
It looks the same to me.

**Comment by kev3978** [comment]
If you have a csv:

A,B,C
D,E,F,G
H,I,J

Then ignoreExcess cols will result in 3 lines being read:
"A", "B", "C"
"D", "E", "F"
"H", "I", "J"

and skipMissMatchedRow will result in 2 lines being read:
"A", "B", "C"
"H", "I", "J"

**Comment by doyaaaaaken** [comment]
Thank you for your detailed explanation, but the `ignoreExcess` option is covered by the `skipMissMatchedRow ` option.

How about making the `skipMissMatchedRow ` option deprecated, and introducing a new option `differentFieldLengthRow`.

The new option can take four values.
1. ERROR (default value) :  Throw exception. This behavior is the same as `skipMissMatchedRow = false` and canonical according to  the [RFC4180](https://www.ietf.org/rfc/rfc4180.txt).
2. IGNORE: This behavior is the same as `skipMissMatchedRow = true`.
3. IGNORE_IF_EXCESS: This behavior is the same as the `ignoreExcess ` option.
4. IGNORE_IF_SHORT: This behavior is opposite to the `ignoreExcess ` option.

**Comment by doyaaaaaken** [comment]
I agree with you. 👍 
- The `IGNORE_IF_SHORT` option value which I suggested is not necessary.
- The specification of the `differentLengthFieldRow`option which you suggested sounds good.

**Comment by kev3978** [comment]
Hi @doyaaaaaken - absolutely, I will alter it later this week.

**Comment by kev3978** [comment]
@doyaaaaaken I've just thought, there could be a case where the user wants both the TRIM_EXCESS and IGNORE options, e.g. they want to trim the excess columns if possible, or ignore the row if there are fewer than expected. With that in mind, I have reverted back to my original solution and updated the README to reflect that change. I've also added another test case.

**Comment by doyaaaaaken** [comment]
@kev3978 
> I've just thought, there could be a case where the user wants both the TRIM_EXCESS and IGNORE options,

Thanks for the great point!

> I have reverted back to my original solution and updated the README to reflect that change.

I would very much appreciate it, but I think we should follow a different way.
The `ignoreExcessCols` option is similar to the `skipMissMatchedRow` option, so it is confusing to users.

My suggestion is we introduce new `insufficientFieldsRow` and `excessFieldsRow` options, and make the `skipMissMatchedRow` option deprecated.
The `insufficientFieldsRow` option can take the value of `ERROR` or `IGNORE`.
The `excessFieldsRow` option can take the value of `ERROR` or `IGNORE` or `TRIM`.
These options are simple so the behavior can be understood easily.

**Comment by kev3978** [comment]
Sounds like a good solution, I will update the PR later this week. 👍

**Comment by kev3978** [comment]
@doyaaaaaken - I've updated the PR with those changes now.

**Review by doyaaaaaken — APPROVED** [review]
LGTM! Thanks a lot!

**Comment by doyaaaaaken** [comment]
Released on version 1.3.0 🚀

**Pull request merged**
